---
version: 2.0
build_arg_defaults:
  EE_BASE_IMAGE: 'hub.lab.example.com/ee-supported-rhel8:2.0'
  EE_BUILDER_IMAGE: 'hub.lab.example.com/ansible-builder-rhel8:2.0'
dependencies:
  galaxy: requirements.yml
